export const USER_LOGIN = "USER_LOGIN";
export const CURRENT_USER = "CURRENT_USER";
export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const CREATE_USER = "CREATE_USER";
export const DELETE_USER = "DELETE_USER";
export const USER_LOGOUT = "USER_LOGOUT";
export const CREATE_FOOD_ITEM = "CREATE_FOOD_ITEM";
export const FETCH_FOOD_ITEMS = "FETCH_FOOD_ITEMS";
